#[[input.net]]
  ## Network interfaces to monitor, empty for all interfaces (default)
  interfaces = ["eth*", "en*"]

  ## Whether to report per-interface stats (true), or aggregate all interfaces (false, default)
  per_nic = false

  ## metrics of network stats to monitor, empty for all (default)
  ## Available metrics:
  ##
  ## bytes_sent, bytes_recv,
  ## packets_sent, packets_recv,
  ## err_in, err_out
  ## drop_in, drop_out
  ##
  #[input.net.filter]
    ## Include only these kinds of network stats, empty for all kinds (default)
    #includes = ["net:bytes_*", "net:packets_*"]

    ## Exclude these kinds of network stats, empty for none (default)
    #excludes = ["net:*err_*", "net:*drop_*"]
