# [[input.opcua]]
  ## OPC UA server endpoint URL
  # endpoint = "opc.tcp://localhost:4840"

  ## Security mode, one of "None", "Sign", "SignAndEncrypt"
  # security_mode = "None"

  ## Security policy, one of
  ## "None", "Prefix", "Basic128Rsa15", "Basic256", 
  ## "Basic256Sha256", "Aes128_Sha256_RsaOaep", "Aes256_Sha256_RsaPss"
  ## 
  # security_policy = "None"

  ## Certificate file path for "SignAndEncrypt" mode
  # certificate = ""

  ## Private key file path for "SignAndEncrypt" mode
  # private_key = ""

  ## Connection retry interval
  # conn_retry_interval = "1s"

  ## If the retry count is set to 0, it will fail after the first attempt.
  # conn_retry_count = 0

  ## Read retry interval
  # read_retry_interval = "100ms"

  ## If the retry count is set to 0, it will fail after the first attempt.
  # read_retry_count = 0

  ## Node ID configuration
  ## name        - measurement name to use in the output
  ## namespace   - OPC UA namespace of the node (integer 0 ~ 3)
  ## id_type     - OPC UA ID type "s" (string), "i" (numeric), "g" (GUID), "b" (opaque)
  ## id          - OPC UA ID
  ##
  ## Use either the inline notation or the table notation, not both.

  ## Inline notation
  # nodes = [
  #   { name = "node1", namespace = "1", id_type = "s", id = "Temperature" },
  #   { name = "node2", namespace = "1", id_type = "s", id = "Pressure" }
  # ]

  ## Table notation
  # [[input.opcua.nodes]]
  #   name = "node1"
  #   namespace = "1"
  #   id_type = "s"
  #   id = "Temperature"
  #
  # [[input.opcua.nodes]]
  #   name = "node2"
  #   namespace = "1"
  #   id_type = "s"
  #   id = "Pressure"
